### ISSUE TITLE
Rebuild Rosetta

### ISSUE THREAD

**Issue by branfosj** [bear-rsg/easybuild-easyconfigs#120]
Just the easyblock changing: https://github.com/bear-rsg/easybuild-easyblocks/pull/20

Rebuild `Rosetta-3.11-foss-2019b-Python-2.7.16.eb`:
* [x] EL7-sandybridge
* [x] EL7-haswell
* [x] EL7-cascadelake
* [x] EL7-haswell-**noib**
* [x] Ubuntu VM

Run test from https://www.rosettacommons.org/docs/latest/application_documentation/rna/rna-denovo ...

**Comment by edmondac** [comment]
Building...

**Comment by edmondac** [comment]
EL7-haswell-noib started with M4, by the way. So it may be some time...

**Comment by edmondac** [comment]
Done
