### ISSUE TITLE
2020a kickoff build

### ISSUE THREAD

**Issue by branfosj** [bear-rsg/easybuild-easyconfigs#178]
`Python-3.8.2-GCCcore-9.3.0.eb`
* [x] EL7-cascadelake
* [x] EL7-haswell
* [x] EL7-power9
* [x] Ubuntu16 VM

`Python-2.7.18-GCCcore-9.3.0.eb`
* [x] EL7-cascadelake
* [x] EL7-haswell
* [x] EL7-power9
* [x] Ubuntu16 VM

`Perl-5.30.2-GCCcore-9.3.0.eb`
* [x] EL7-cascadelake
* [x] EL7-haswell
* [x] EL7-power9
* [x] Ubuntu16 VM

`SciPy-bundle-2020.03-foss-2020a-Python-3.8.2.eb`
* [x] EL7-cascadelake
* [x] EL7-haswell
* [x] EL7-power9
* [x] Ubuntu16 VM

`R-bundle-Bioconductor-3.11-foss-2020a-R-4.0.0.eb`
* [x] EL7-cascadelake
* [x] EL7-haswell
~~* [ ] EL7-power9~~
* [x] Ubuntu16 VM

`HPL-2.3-foss-2020a.eb`
* [x] EL7-cascadelake
* [x] EL7-haswell
* [x] EL7-power9
* [x] Ubuntu16 VM

**Comment by branfosj** [comment]
Part two, for once the new hooks are merged:

Rebuild, in this order: 
* `OpenMPI/4.0.3-GCC-9.3.0`
  * [ ] EL7-cascadelake
  * [ ] EL7-haswell
  * [ ] EL7-power9

* `gompi/2020a`
  * [ ] EL7-cascadelake
  * [ ] EL7-haswell
  * [ ] EL7-power9

* `FFTW/3.3.8-gompi-2020a`
  * [ ] EL7-cascadelake
  * [ ] EL7-haswell
  * [ ] EL7-power9

* `ScaLAPACK/2.1.0-gompi-2020a`
  * [ ] EL7-cascadelake
  * [ ] EL7-haswell
  * [ ] EL7-power9

* `HDF5/1.10.6-gompi-2020a`
  * [ ] EL7-cascadelake
  * [ ] EL7-haswell
  * [ ] EL7-power9

* `netCDF/4.7.4-gompi-2020a`
  * [ ] EL7-cascadelake
  * [ ] EL7-haswell
  * [ ] EL7-power9

* `foss/2020a`
  * [ ] EL7-cascadelake
  * [ ] EL7-haswell
  * [ ] EL7-power9

* `SciPy-bundle/2020.03-foss-2020a-Python-3.8.2`
  * [ ] EL7-cascadelake
  * [ ] EL7-haswell
  * [ ] EL7-power9

* `HPL/2.3-foss-2020a`
  * [ ] EL7-cascadelake
  * [ ] EL7-haswell
  * [ ] EL7-power9

* `R/4.0.0-foss-2020a`
  * [ ] EL7-cascadelake
  * [ ] EL7-haswell

* `ncdf4/1.17-foss-2020a-R-4.0.0`
  * [ ] EL7-cascadelake
  * [ ] EL7-haswell

* `R-bundle-Bioconductor/3.11-foss-2020a-R-4.0.0`
  * [ ] EL7-cascadelake
  * [ ] EL7-haswell

**Comment by edmondac** [comment]
I've moved aside the old modules and software for 2020a for EL7, and will build again:

`Python-3.8.2-GCCcore-9.3.0.eb`
* [] EL7-cascadelake
* [] EL7-haswell
* [] EL7-power9

`Python-2.7.18-GCCcore-9.3.0.eb`
* [] EL7-cascadelake
* [] EL7-haswell
* [] EL7-power9

`Perl-5.30.2-GCCcore-9.3.0.eb`
* [] EL7-cascadelake
* [] EL7-haswell
* [] EL7-power9

`SciPy-bundle-2020.03-foss-2020a-Python-3.8.2.eb`
* [] EL7-cascadelake
* [] EL7-haswell
* [] EL7-power9

`R-bundle-Bioconductor-3.11-foss-2020a-R-4.0.0.eb`
* [] EL7-cascadelake
* [] EL7-haswell

`HPL-2.3-foss-2020a.eb`
* [] EL7-cascadelake
* [] EL7-haswell
* [] EL7-power9

**Comment by edmondac** [comment]
All done!
