### ISSUE TITLE
easyconfigs/a/Aspera-CLIAspera-CLI-3.9.6.1467.159c5b1.eb

### ISSUE THREAD

**Issue by sihart25** [bear-rsg/easybuild-easyconfigs#666]
For INC1146489 - `Aspera-CLI-3.9.6.1467.159c5b1.eb`

  

- [x]  Assigned to reviewers (usually everyone in apps team)
  
Default:
 

- [x]  EL8-cascadelake
- [x]  EL8-haswell

**Comment by sihart25** [comment]
in 2020b

**Comment by edmondac** [comment]
Done
