### ISSUE TITLE
2021a

### ISSUE THREAD

**Issue by branfosj** [bear-rsg/easybuild-easyconfigs#703]
Notes:
* use direct login (at least for R)
* I filled `/tmp` while build on Ubuntu

* [x] merge #706
* [x] merge #705
* [x] merge https://github.com/bear-rsg/easybuild-framework/pull/25

`R-bundle-Bioconductor-3.13-foss-2021a-R-4.1.0.eb` `SciPy-bundle-2021.05-foss-2021a.eb`:
* [x] EL8-cascadelake
* [x] EL8-haswell
* [x] U20-haswell

`SciPy-bundle-2021.05-foss-2021a.eb`:
* [x] EL8-power9

post install:
* [x] eb post install
* [x] set 2021a as not loaded by default on BEAR Apps

**Comment by edmondac** [comment]
All done
