### ISSUE TITLE
iomkl 2021a HPL and OSU

### ISSUE THREAD

**Issue by branfosj** [bear-rsg/easybuild-easyconfigs#807]
`HPL-2.3-iomkl-2021a.eb OSU-Micro-Benchmarks-5.7.1-iompi-2021a.eb`
* [x] EL8-icelake
* [x] EL8-cascadelake
* [x] EL8-haswell

**Comment by orbsmiv** [comment]
Done! https://bear-apps.bham.ac.uk/applications/2021a/HPL/2.3-iomkl-2021a/
