### ISSUE TITLE
Build SciPy bundle for Python 2

### ISSUE THREAD

**Issue by afraz-ahmed** [bear-rsg/easybuild-easyconfigs#94]
https://github.com/bear-rsg/easybuild-easyconfigs/blob/2019b/easybuild/easyconfigs/s/SciPy-bundle/SciPy-bundle-2019.10-foss-2019b-Python-2.7.16.eb

`SciPy-bundle-2019.10-foss-2019b-Python-2.7.16.eb`
* [x] EL7-cascadelake
* [x] EL7-haswell
* [x] EL7-sandybridge
* [x] EL7-power9
* [x] Ubuntu16 VM

**Comment by branfosj** [comment]
closing, as these have been built
